# Generated by Django 5.0.3 on 2024-04-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=15)),
                ('desc', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('image', models.URLField(verbose_name='image url')),
                ('amenities', models.TextField()),
                ('amenityIcons', models.TextField()),
            ],
        ),
    ]
